import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en-US">
      <body className={cn('text-base antialiased', inter.className)}>{children}</body>
    </html>
  );
}